version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: python src/main.py

  evaluate:
    build: .
    command: >
      /bin/bash -c "sleep 10 && python scripts/evaluate.py"
    depends_on:
      - api
